---
title: "TidyX Episode 31 - Reactable"
author: "Patrick Ward & Ellis Hughes"
date: "October 9, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Packages & Data

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(reactable)
library(ggridges)
library(sparkline)
library(pagedtable) #thebioengineer/pagedtable

theme_set(theme_light())

```

```{r data}

tt <- tt_load("2020-10-06")

tt

ncaa <- tt$tournament

```


Win Probabilities

```{r}

ncaa_table <- ncaa %>%
  count(seed, tourney_finish) %>%
  mutate(
    tourney_finish = factor(
      tourney_finish,
      levels = c(
        "1st","2nd","RSF","RF","NSF","N2nd","Champ"
      )
    ),
  ) %>% 
  group_by(seed) %>%
  mutate(
    Pct = n / sum(n)
  )

ncaa_table %>%
  select(seed, tourney_finish, Pct) %>%
  filter(
    tourney_finish != "OR",
    !is.na(seed)
    ) %>%
  pivot_wider(
    names_from = "tourney_finish",
    values_from = "Pct"
  ) %>%
  select(
    seed,
    !!levels(ncaa_table$tourney_finish)
  ) %>% 
  reactable(columns = list(
    '1st' = colDef(format = colFormat(percent = T, digits = 1), na = "-"),
    '2nd' = colDef(format = colFormat(percent = T, digits = 1), na = "-"),
    Champ = colDef(format = colFormat(percent = T, digits = 1), na = "-"),
    'N2nd' = colDef(format = colFormat(percent = T, digits = 1), na = "-"),
    NSF = colDef(format = colFormat(percent = T, digits = 1), na = "-"),
    RF = colDef(format = colFormat(percent = T, digits = 1), na = "-"),
    RSF = colDef(format = colFormat(percent = T, digits = 1), na = "-")
    ),
  defaultPageSize = 16)


```


