---
title: "Episode 83 - Naive Bayes Classifier"
author: "Patrick Ward"
date: "11/10/2021"
output: html_document
---


## Load Packages & Data

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidymodels)
library(palmerpenguins)
library(discrim) ## for naive bayes

penguins %>%
  head()

penguins %>%
  summarize(across(.cols = everything(), ~sum(is.na(.))))

penguins %>%
  filter(is.na(sex))

## Remove the two observations with all data missing
penguins_cleaned <- penguins %>%
  filter(!is.na(bill_depth_mm))

```


## Split Data

**Train/Test Split**

```{r}

set.seed(6923)
penguin_split <- initial_split(penguins_cleaned, strata = "species")

train <- training(penguin_split)
test <- testing(penguin_split)

```


**Cross Validation**

```{r}
set.seed(3344)
cv_folds <- vfold_cv(
  data = train, 
  v = 5
  ) 

cv_folds
```


## Model Specification

```{r}

library(klaR)

nb_model <- naive_Bayes() %>% 
  set_mode("classification") %>% 
  set_engine("klaR")

```


## Recipe


```{r}

penguins_rec <- recipe(
    species ~ . ,
    data = train
  ) %>%
  step_impute_knn(
    sex,
    neighbors = 3
  ) %>% 
  update_role(
    year, island,
    new_role = "ID"
  )

```


## Workflow

```{r}

penguins_wf <- workflow() %>% 
  add_recipe(penguins_rec) %>% 
  add_model(nb_model)

```


## Fit Model on Training Data

**Fit to CV-Folds**

```{r}

nb_fit <- penguins_wf %>% 
  fit_resamples(
    resamples = cv_folds
  )

collect_metrics(nb_fit)

```


## Make Predictions on Test Data


```{r}

nb_final <- penguins_wf %>% 
  last_fit(
    split = penguin_split
  )

collect_metrics(nb_final)


nb_test_pred <- bind_cols(
  test,
  nb_final %>% collect_predictions() %>% dplyr::select(starts_with(".pred_"))
)



table("predicted class" = nb_test_pred$.pred_class,
      "observed class" = nb_test_pred$species)

nb_test_pred %>% 
  roc_curve(
    truth = species,
    .pred_Adelie, .pred_Chinstrap, .pred_Gentoo
  ) %>% 
  autoplot()

```

