---
title: "using_tidyxbayes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{using_tidyxbayes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyxbayes)
library(tidyverse)
```


## Beta Distribution

```{r beta_example}

pop_avg <- lahman_batting_2010 %>%
  filter(AB >= quantile(AB, probs = 0.75)) %>%
  pull(batting_avg) %>%
  mean()

pop_var <- lahman_batting_2010 %>%
   filter(AB >= quantile(AB, probs = 0.75)) %>%
   pull(batting_avg) %>%
   var()

pop_avg
pop_var
sqrt(pop_var)

## Using the function

batting_avg_params <- get_beta_parameters(
   population_avg = pop_avg,
   population_var = pop_var
 )

ba_alpha_prior <- batting_avg_params$alpha
ba_beta_prior <- batting_avg_params$beta

# Looking at the entire population

lahman_batting_2010 %>%
  mutate(
    posterior_batting_avg = posterior_beta_mu(
      ba_alpha_prior, 
      ba_beta_prior,
      n = AB, 
      success = H
      ),
    pop_avg = pop_avg
    ) %>%
  ggplot(
    aes(x = batting_avg, 
        y = posterior_batting_avg
        )) +
  geom_point(aes(size = AB),
             color = "black",
             alpha = 0.8) +
  geom_hline(aes(yintercept = pop_avg),
             color = "green",
             linewidth = 1.2,
             linetype = "dashed") +
  geom_abline(intercept = 0,
              slope = 1,
              linewidth = 1.2,
              color = "green")
  
# Looking at a few players
set.seed(559)

a_few_players <- lahman_batting_2010 %>%
  sample_n(size = 10) %>%
  mutate(posterior_batting_avg = posterior_beta_mu(ba_alpha_prior, ba_beta_prior, n = AB, success = H),
         posterior_batting_sd = posterior_beta_sd(ba_alpha_prior, ba_beta_prior, n = AB, success = H))

a_few_players %>%
  knitr::kable()

a_few_players %>%
  mutate(
    batting_avg = coalesce(batting_avg, 0),
    playerid_year = paste0(playerID,"-",yearID)
    ) %>%
  ggplot(aes(x = batting_avg, y = playerid_year)) +
  geom_point(aes(size = AB)) +
  geom_errorbar(aes(xmin = posterior_batting_avg - posterior_batting_sd,
                    xmax = posterior_batting_avg + posterior_batting_sd),
                width = 0,
                size = 1.1) +
  geom_point(aes(x = posterior_batting_avg),
             color = "red",
             alpha = 0.5,
             size = 4)
```


## Gamma Distribution

```{r gamma_example}


rpg_mean <- mean(lahman_team_runs_2010$runs_per_game)
rpg_var <- var(lahman_team_runs_2010$runs_per_game)

rpg_mean
rpg_var
sqrt(rpg_var)

rpg_params <- get_gamma_parameters(population_avg = rpg_mean,
                                   population_var = rpg_var)

rpg_alpha_prior <- rpg_params$alpha
rpg_beta_prior <- rpg_params$beta

team_posterior <- lahman_team_runs_2010 %>%
  mutate(
      posterior_rpg_avg = posterior_gamma_mu(rpg_alpha_prior, rpg_beta_prior, G, R),
      posterior_rpg_sd = posterior_gamma_sd(rpg_alpha_prior, rpg_beta_prior, G, R)
  ) 

team_posterior %>%
  head() %>%
  knitr::kable()

team_posterior %>%
  mutate(diff = runs_per_game - posterior_rpg_avg) %>%
  ggplot(aes(x = diff)) +
  geom_histogram(color = "black",
                 fill = "light grey") +
  geom_vline(xintercept = 0,
             color = "red",
             size = 1.2,
             linetype = "dashed")

team_posterior %>%
  ggplot(aes(x = posterior_rpg_avg, y = runs_per_game)) +
  geom_point(size = 3.5,
             shape = 21,
             fill = "grey",
             color = "black") +
  geom_abline(intercept = 0,
              slope = 1,
              color = "red",
              size = 2,
              linetype = "dashed")


```
